carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

playzoneshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from games.views import GameListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GameListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.registrar, name='registro'),
    path('juegos/', include('games.urls')),
    path('carrito/', include('carts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Administrador de PlayZone Shop'

carts/models.py
from django.db import models

from users.models import User
from games.models import Game
from django.db.models.signals import pre_save, m2m_changed, post_save
import uuid
import decimal

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    games = models.ManyToManyField(Game, through='CartGames')
    total = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.total = sum([ 
           cg.quantity * cg.game.precio for cg in self.games_related()
         ])
        self.save()

    def games_related(self):
        return self.cartgames_set.select_related('game')

class CartGamesManager(models.Manager):

    def create_or_update_quantity(self, cart, game, quantity=1):
        object, created = self.get_or_create(cart=cart, game=game)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)
        return object

class CartGames(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartGamesManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()
    
def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_total(sender, instance, *args, **kwargs):
    instance.cart.update_totals()


pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_total, sender=CartGames)
m2m_changed.connect(update_totals, sender=Cart.games.through)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Cart 
from .utils import get_or_create_cart  

from games.models import Game
from .models import CartGames

def cart(request):

    cart = get_or_create_cart(request)    

    return render(request, 'carts/cart.html', {
        'cart': cart,
    })

def add(request):
    cart = get_or_create_cart(request)
    game = get_object_or_404(Game, pk=request.POST.get('game_id'))
    quantity = int(request.POST.get('quantity', 1))

    #cart.games.add(game, through_defaults={
    #    'quantity': quantity
    #})

    cart_games = CartGames.objects.create_or_update_quantity(cart=cart, 
                                                                game=game, 
                                                                quantity=quantity
                                                            )

    return render(request, 'carts/add.html', {
        'game': game,
    })

def remove(request):
    cart = get_or_create_cart(request)
    game = get_object_or_404(Game, pk=request.POST.get('game_id'))

    cart.games.remove(game)

    return redirect('carts:cart')

carts/templates/carts/snippets/add.html
{% load humanize %}

<form action="{% url 'carts:add' %}" method="Post" class="">
    {% csrf_token %}
    <input type="hidden" name="game_id" value="{{game.id}}">
    <div class="">
        <button type="button" class="btn btn-info d-inline" id="remove">-</button>
        <input id="quantity" name="quantity" type="number" value="1" class="form-control col-sm-1 d-inline" readonly>
        <button type="button" class="btn btn-info" id="add">+</button>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Agregar al carrito</button>
</form>

<script>
    const add = document.querySelector('#add');
    const remove = document.querySelector('#remove');
    const quantity = document.querySelector('#quantity')

    add.addEventListener('click', function(){
        quantity.value = parseInt(quantity.value) + 1;
    });

    remove.addEventListener('click', function(){
        value = parseInt(quantity.value);

        if(value != 1){
            value = value -1;
        }

        quantity.value = value
    });

</script>

carts/templates/carts/snippets/addindex.html
<form action="{% url 'carts:add' %}" method="Post" class="text-center">
    {% csrf_token %}
    <input type="hidden" name="game_id" value="{{game.id}}">
    <button type="submit" class="btn btn-primary mt-3">Agregar al carrito</button>
</form>

carts/templates/carts/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="Post" class="text-center">
    {% csrf_token %}
    <input type="hidden" name="game_id" value="{{game.id}}">
    <button type="submit" class="btn btn-link text-danger">Eliminar del carrito</button>
</form>