carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

games/urls.py
from django.urls import path
from .views import GameDetailView, GameSearchListView

app_name='juego'

urlpatterns = [

    path('search', GameSearchListView.as_view(), name='search'),
    path('<slug:slug>', GameDetailView.as_view(), name='juego'),
    
]

playzoneshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from games.views import GameListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GameListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.registrar, name='registro'),
    path('juegos/', include('games.urls')),
    path('carrito/', include('carts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Administrador de PlayZone Shop'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Play Zone Shop</title>
</head>
<body style="background-color:#19273a">
  {% include 'navbar.html' %}
  <div class="container">
    <div class="row">
      {% block content %}

      {% endblock %}
    </div>
  </div>
</body>




<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
{% include 'footer.html'%}

templates/footer.html
<footer>
    <div class="container-fluid text-center text-md-left" style="background-color: #1E375A;" >
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3"><br>
                <h5 class="text-uppercase font-weight-bold" style="color: whitesmoke;" >Proyecto Tienda Online</h5>
                <p class="text-justify" style="color: whitesmoke">Este proyecto fue desarrollado usando HTML, CSS (bootstrap), Javascript y Python (Django)</i>.
                </p>
            </div>  
            <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-6 mb-md-0 mb-3 text-center"> <br>
                    <h5 class="text-uppercase font-weight-bold" style="color: whitesmoke;">Desarrollado por: </h5>
                    <p class="text-light">Johan Esteban Cañas <strong>Estudiante de Ingeniería de Software</strong></p>
                </div>  
        </div>  
    </div>

    <div class="footer-copyright text-center py-3 text-light" style="background-color: #343a40;" >
        <p>
        © 2020 Copyright - PlayZoneShop
        </p>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
  <div class="col-12">
    {% if messages %}
    {% for message in messages %}
      <div class="alert mt-4">
        <button type="button" class="close text-light pt-4" data-dismiss="alert">x</button>
        <h3 class="text-light pt-4">{{ message }}</h3>
      </div>
    {% endfor%}
  {% endif %}
  </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="/static/img/comandos.jpg" class="d-block w-100" alt="..." class="img-fluid">
                      </div>
                      <div class="carousel-item">
                        <img src="/static/img/fortnite.jpg" class="d-block w-100" alt="..." class="img-fluid">
                      </div>
                      <div class="carousel-item">
                        <img src="/static/img/fondo-de-pantalla-juegos-5.jpeg" class="d-block w-100" alt="..." class="img-fluid">
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                  <section> 
                      <div class="container" style="background-color:#1e3049;"><br>
                        {% include 'games/snippets/search.html '%}
                        <h3 style="color: whitesmoke;">Juegos de acción</h3>
                        <!-- INICIO DE PRODUCTOS ACCION-->
                        <div class="card-deck">
                          {% for game in object_list%}
                            {% if game.categoria == 'Juegos de accion'%}
                              <div class="card">
                                <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                                  <p class="card-text text-justify pb-3">{{game.descripcion}}</p>
                                  <h3 class="text-center text-danger">$ {{game.precio | intcomma }}</h3><br>
                                    <div class="text-center">
                                      <button class="btn btn-primary"><a href="{% url 'juego:juego'  game.slug %}" class="text-light">
                                                                        Agregar al carrito 
                                                                      </a>
                                      </button>
                                    </div>
                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                        </div>
                        </div><br>
                        <br><!--FIN DEL PRODUCTO ACCION-->
                        <center> <!--BANNER PUBLICIDAD-->
                          <img src="{% static 'img/banner_publicidad_2.jpg' %}" width="95%" alt=""><br><br>
                        </center>
                      <!-- INICIO DE PRODUCTOS SIMULACION-->
                      <div class="container" style="background-color:#1e3049;"><br>
                        <h3 style="color: whitesmoke;">Juegos de simulación</h3>
                        <!-- INICIO DE PRODUCTOS ACCION-->
                        <div class="card-deck">
                          {% for game in object_list%}
                            {% if game.categoria == 'Juegos de simulacion'%}
                              <div class="card">
                                <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                                  <p class="card-text text-justify">{{game.descripcion}}</p>
                                  <h3 class="text-center text-danger">${{game.precio | intcomma}}</h3><br>
                                  <div>
                                    {% include 'carts/snippets/addindex.html' %}
                                  </div>
                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                        </div>
                        </div><br><!--FIN DEL PRODUCTO SIMULACION-->
                      <center> <!--BANNER PUBLICIDAD-->
                      <img src="{% static 'img/banner_publicidad.jpg' %}" width="95%" alt=""><br><br>
                    </center>
                      <!-- INICIO DE PRODUCTOS DEPORTES-->
                      <div class="container" style="background-color:#1e3049;"><br>
                        <h3 style="color: whitesmoke;">Juegos de deportes</h3>
                        <!-- INICIO DE PRODUCTOS ACCION-->
                        <div class="card-deck">
                          {% for game in object_list %}
                            {% if game.categoria == 'Juegos de deportes'%}
                              <div class="card">
                                <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                                  <p class="card-text text-justify">{{game.descripcion}}</p>
                                  <h3 class="text-center text-danger">${{game.precio | intcomma }}</h3><br>
                                  <div>
                                    {% include 'carts/snippets/addindex.html' %}
                                  </div>
                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                        </div>
                        </div><br><!--FIN DEL PRODUCTO DEPORTES-->
                
                      <!-- INICIO DE PRODUCTOS AVENTURA-->
                      <div class="container" style="background-color:#1e3049;"><br>
                        <h3 style="color: whitesmoke;">Juegos de aventura</h3>
                        <!-- INICIO DE PRODUCTOS ACCION-->
                        <div class="card-deck">
                          {% for game in object_list%}
                            {% if game.categoria == 'Juegos de aventura'%}
                              <div class="card">
                                <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                                  <p class="card-text text-justify">{{game.descripcion}}</p>
                                  <h3 class="text-center text-danger">${{game.precio | intcomma }}</h3><br>
                                  <div>
                                    {% include 'carts/snippets/addindex.html' %}
                                  </div>
                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                        </div>
                        </div><br><!--FIN DEL PRODUCTO AVENTURA-->
                      <center> <!--BANNER PUBLICIDAD-->
                        <img src="{% static 'img/banner_publicidad.jpg' %}" width="95%" alt=""><br><br>
                      </center>
                      <!-- INICIO DE PRODUCTOS PLATAFORMAS-->
                      <div class="container" style="background-color:#1e3049;"><br>
                        <h3 style="color: whitesmoke;">Juegos de plataformas</h3>
                        <!-- INICIO DE PRODUCTOS ACCION-->
                        <div class="card-deck">
                          {% for game in object_list %}
                            {% if game.categoria == 'Juegos de plataformas'%}
                              <div class="card">
                                <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                                  <p class="card-text text-justify">{{game.descripcion}}</p>
                                  <h3 class="text-center text-danger">${{game.precio | intcomma }}</h3><br>
                                  <div>
                                    {% include 'carts/snippets/addindex.html' %}
                                  </div>
                                </div>
                              </div>
                            {% endif %}
                          {% endfor %}
                        </div>
                        </div><br><!--FIN DEL PRODUCTO PLATAFORMAS-->
                      <center> <!--BANNER PUBLICIDAD-->
                        <img src="{% static 'img/banner_publicidad_3.jpg' %}" width="95%" alt=""><br><br>
                      </center>
                
                  <!-- INICIO DE PRODUCTOS PUZZLE-->
                  <div class="container" style="background-color:#1e3049;"><br>
                    <h3 style="color: whitesmoke;">Juegos de puzzle</h3>
                    <!-- INICIO DE PRODUCTOS ACCION-->
                    <div class="card-deck">
                      {% for game in object_list %}
                        {% if game.categoria == 'Juegos de puzzle'%}
                          <div class="card">
                            <img src="{{game.imagen.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <a href="{% url 'juego:juego'  game.slug %}"><h5 class="card-title">{{game.nombre}}</h5></a>
                              <p class="card-text text-justify">{{game.descripcion}}</p>
                              <h3 class="text-center text-danger">${{game.precio | intcomma }}</h3><br>
                              <div>
                                {% include 'carts/snippets/addindex.html' %}
                              </div>
                            </div>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </div>
                    </div><br><!--FIN DEL PRODUCTO PUZLE-->
            </div>
        </div>
    </div>

{% endblock%}

templates/navbar.html
{% url 'login' as login %}
{% url 'registro' as registro %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="/" class="navbar-brand">PlayZone Shop</a>

    <button class="navbar-toggler navbar-toggler-right" type="button" name="button" 
        data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div id="navb" class="navbar-collapse collapse-hide">

        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}" >
                <a class="nav-link" href="{{cart}}">
                    Carrito <span class="text-light"><i class="fa fa-shopping-cart"></i></span>
                </a>
            </li>

        </ul>
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{{logout}}" class="nav-link">Salir</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{login}}" class="nav-link">Ingresar</a>
                </li>
                <li class="navbar-item {% if request.path == registro %}active{% endif %}">
                    <a href="{{registro}}" class="nav-link">Registro</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>